# Data Formatting for MCQ Classification

This notebook converts the original MCQ dataset into a format suitable
for machine learning and transformer models.

In [1]:
import pandas as pd

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

#Function

In [4]:
def create_mcq_pairs(df):
    rows = []
    option_columns = ["A", "B", "C", "D", "E"]
    for _, row in df.iterrows():
        for option in option_columns:
            rows.append({
                "id": row["id"],
                "prompt": row["prompt"],
                "option": row[option],
                "option_id": option,
                "label": int(option == row["answer"])
            })
    return pd.DataFrame(rows)

In [5]:
train_pairs = create_mcq_pairs(train)

#Verify

In [6]:
print(train_pairs.shape)
train_pairs.head(10)

(10000, 5)

,id,prompt,option,option_id,label
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,A,0
1,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans do not e...,B,1
2,1,Pick the best possible answer: What is Martin ...,Martin Heidegger does not believe in the exist...,C,0
3,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that the relationshi...,D,0
4,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that time is an illu...,E,0
5,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,A,1
6,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,B,0
7,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,C,0
8,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,D,0
9,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,E,0

In [10]:
train_pairs["label"].value_counts()

label
0    8000
1    2000
Name: count, dtype: int64

In [11]:
question_id = train_pairs.iloc[0]["id"]
train_pairs[train_pairs["id"] == question_id]

,id,prompt,option,option_id,label
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,A,0
1,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans do not e...,B,1
2,1,Pick the best possible answer: What is Martin ...,Martin Heidegger does not believe in the exist...,C,0
3,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that the relationshi...,D,0
4,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that time is an illu...,E,0

In [12]:
train_pairs.to_csv("train_pairs.csv",index=False)